auth:
  postgresPassword: "postgres"
  database: "inference_platform"
primary:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    size: 1Gi
